### ISSUE TITLE
"mros2" branch is not the one corresponding to the Ver.0.4.0 

### ISSUE THREAD

**Issue by smoriemb** [mROS-base/embeddedRTPS#10]
First, I apologize for making a mistake updating the branch below to the original main (Can I revert forcefully?).
https://github.com/mROS-base/embeddedRTPS/tree/mros2_track-ertps-1410a87

The current mROS2 repository refers to a commit ID directly, not a branch, as below.
````
Agent-less: a node on mROS 2 autonomously discovers communication nodes on the host with the feature of embeddedRTPS. It means no agent/bridge is required for pub/sub communication from the embedded devices.
    mros2 currently uses embeddedRTPS @ 1410a87 as it is.
````
But, it is inconvenient to make some pull requests if there is no branch to be based.

**Comment by smoriemb** [comment]
Sorry again, I created this issue in the wrong repository.  I've already created this in a proper repository, as below.

https://github.com/mROS-base/embeddedRTPS/issues/10

So, I closed this issue.

**Comment by takasehideki** [comment]
OK, I guess what you want is to clean up the messy branches.
I'll reorganize `branch` / `tag` as the following.

- mros2 / [1410a87](https://github.com/mROS-base/embeddedRTPS/tree/1410a8776660244249a84031ffa78c9bdaa45e19)
  - used in mros2 v0.4.0, that is the latest version.
- master / [96060d9](https://github.com/embedded-software-laboratory/embeddedRTPS/commit/96060d995d7247b9e9b033b7aa6391b90e689786)
  - the latest on the original repo in embedded-software-laboratory
  - I think it is also convenient when we would like to create a PR to the original repo
  - `mros2_track-ertps-1410a87` will be removed
- mros2_v0.3.2_asp3 / 501987d23540b4aeed7cb9703db36e58d976c10b
  - used in mros2 v0.3.2, that is older version (current `mros2` branch)
  - it still used in mros2-asp3-f767zi

And also, I decided to throw all the old branches out the window (`dev_for_mros2`, `mros2_v0.2.0_rc`, `mros2_v0.4.0_rc`)

**Comment by takasehideki** [comment]
@smoriemb I've reorganized them. Note that `mros2` is still the default branch. If your request could be satisfied, please close this issue.

**Comment by smoriemb** [comment]
Thanks for your support.
Then, after closing this issue, I will create a pull-request to the "mros2" branch.
